upgrade-version: [{
  upgrade-path: [
    {
      version: 14.3,
      upgrade-type: null,
    },
    {
      version: '14.11',
      upgrade-type: minor,
    },
    { 
      version: target.latest,
      upgrade-type: major,
    }
  ],
  babelfishpg_tsql_server_collation_name: chinese_prc_ci_as
},
{
  upgrade-path: [
    {
      version: 15.2,
      upgrade-type: null
    },
    {
      version: target.latest,
      upgrade-type: minor
    }
  ],
  babelfishpg_tsql_server_collation_name: chinese_prc_ci_as
}]
