upgrade-version: [{
  upgrade-path: [
    {
      version: 13.6,
      upgrade-type: null,
    },
    {
      version: 14.6,
      upgrade-type: major,
    },
    { 
      version: target.latest,
      upgrade-type: major,
    }
  ]
},
{
  upgrade-path: [
    {
      version: source.latest,
      upgrade-type: null
    },
    { 
      version: target.latest,
      upgrade-type: major
    }
  ]
},
{
  upgrade-path: [
    {
      version: 13.6,
      upgrade-type: null
    },
    {
      version: '14.12',
      upgrade-type: major
    },
    {
      version: 15.7,
      upgrade-type: major
    },
    { 
      version: target.latest,
      upgrade-type: major
    }
  ]
},
{
  upgrade-path: [
    {
      version: 15.5,
      upgrade-type: null
    },
    {
      version: 15.7,
      upgrade-type: minor
    },
    { 
      version: target.latest,
      upgrade-type: major
    }
  ],
  babelfishpg_tsql_server_collation_name: chinese_prc_ci_as
}
]