upgrade-version: [{
  upgrade-path: [
    {
      version: 13.6,
      upgrade-type: null,
    },
    {
      version: 14.6,
      upgrade-type: major,
    },
    { 
      version: target.latest,
      upgrade-type: major,
    }
  ]
}
]